#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d#;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [1]:
import numpy as np

#THE BASICS :

#initialize array

In [2]:
#THE BASICS :
#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [3]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [4]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [5]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [6]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [7]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [8]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


In [9]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]


np.float64(4.2)

In [10]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [11]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [12]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [13]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

# 3-d Example

In [14]:
c=np.array([[
    [1,2],[2,3]
    ],
    [
    [3,4],[4,5]
     ]
     ])

In [15]:
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [16]:
type(c)

numpy.ndarray

In [17]:
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

In [19]:
c.size

8

> calculate the space took for c numpy array

c.dtype

In [20]:
c.dtype

dtype('int64')

In [21]:
c.itemsize * c.size

64

In [22]:
print("Specified element is :",c[0,1,1])

Specified element is : 3


In [23]:
c[1,1,1] = 100
c

array([[[  1,   2],
        [  2,   3]],

       [[  3,   4],
        [  4, 100]]])

# initilizing different types of arrays

In [24]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
zm=np.zeros((3,4))#3 rows and 4 column

In [26]:
zm.ndim

2

In [27]:
zm.shape

(3, 4)

> all 1's matrix

In [28]:
ones = np.ones((3,3),dtype=int)

In [29]:
ones[1,1] = 100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]])

In [30]:
#any other number
np.full(ones.shape,33)

array([[33, 33, 33],
       [33, 33, 33],
       [33, 33, 33]])

> reuse the already existing array and assign one value to en

In [31]:
np.random.random_sample((2,3))

array([[0.6989944 , 0.11221936, 0.16871472],
       [0.70024367, 0.4283746 , 0.66093448]])

In [32]:
np.random.rand(2,3)

array([[0.92943425, 0.19144159, 0.33285868],
       [0.70102158, 0.80508233, 0.06539854]])

In [33]:
np.random.randint(6,9,size=(3,3))

array([[8, 7, 6],
       [6, 6, 6],
       [8, 6, 6]], dtype=int32)

>identity matrix

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])